# Generated by Django 5.0.2 on 2024-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(choices=[(0, 'Highly dissatisfied'), (1, 'Dissatisfied'), (2, 'Neither satisfied nor dissatisfied'), (3, 'Somewhat satisfied'), (4, 'Satisfied'), (5, 'Highly satisfied'), (6, 'Very satisfied'), (7, 'Delighted'), (8, 'Extremely delighted'), (9, 'Promoter'), (10, 'Detractor')])),
            ],
        ),
    ]
