# Generated by Django 5.0.2 on 2024-02-09 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_created_at_survey_creator_survey_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='unique_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
