# Generated by Django 5.0.2 on 2024-02-09 04:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_survey_unique_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='nps_score',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='description',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.submission'),
        ),
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='submission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=128)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.option'),
        ),
        migrations.DeleteModel(
            name='NPS',
        ),
    ]
