# Generated by Django 5.0.2 on 2024-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_questioncategory_alter_question_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='nps_indicator',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
