# Generated by Django 5.0.2 on 2024-02-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_option_nps_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
