# Generated by Django 5.0.2 on 2024-02-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_option_answer_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='nps_indicator',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='option',
            name='text',
        ),
        migrations.AddField(
            model_name='option',
            name='value',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
