# Generated by Django 5.0.2 on 2024-02-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_option_nps_indicator_remove_option_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
    ]
