# Generated by Django 5.0.2 on 2024-02-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_option_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='label',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
