# Generated by Django 5.0.2 on 2024-02-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_remove_option_label_remove_option_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='nps_indicator',
        ),
    ]
