# Generated by Django 5.0.2 on 2024-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_option_nps_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='option',
        ),
        migrations.AddField(
            model_name='answer',
            name='nps_score',
            field=models.IntegerField(choices=[(-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='is_nps_question',
            field=models.BooleanField(default=False),
        ),
    ]
