# Generated by Django 5.0.2 on 2024-02-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_remove_answer_option_answer_nps_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='nps_indicator',
            new_name='nps_value',
        ),
        migrations.AddField(
            model_name='option',
            name='is_nps_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
