# Generated by Django 5.0.2 on 2024-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_surveyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='survey.surveyquestion'),
        ),
    ]
