# Generated by Django 5.0.2 on 2024-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_survey_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='is_nps_question',
            field=models.BooleanField(default=False),
        ),
    ]
