# Generated by Django 5.0.2 on 2024-02-23 15:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_company_chosen_survey_questions'),
        ('survey', '0023_surveyquestion_is_nps_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.company'),
        ),
        migrations.AddField(
            model_name='survey',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='survey',
            name='duration',
            field=models.CharField(choices=[('7', '7 days'), ('15', '15 days'), ('30', '30 days')], default='7', max_length=10),
        ),
        migrations.AddField(
            model_name='survey',
            name='frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='survey',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
