# Generated by Django 5.0.2 on 2024-02-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_question_is_ees_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
