# Generated by Django 5.0.2 on 2024-02-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_promoter_score', '0003_questioncategory_survey_alter_userscore_group_and_more'),
        ('survey', '0018_option_nps_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='survey.question'),
        ),
        migrations.AddField(
            model_name='userscore',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='survey.survey'),
        ),
    ]
