# Generated by Django 5.0.2 on 2024-02-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net_promoter_score', '0004_userscore_question_userscore_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
