# Generated by Django 5.0.2 on 2024-02-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_promoter_score', '0006_alter_userscore_question'),
        ('survey', '0027_questioncategory_is_nps_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='questioncategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='survey.questioncategory'),
        ),
    ]
