# Generated by Django 5.0.2 on 2024-02-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_promoter_score', '0007_userscore_questioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='is_nps_question',
            field=models.BooleanField(default=False),
        ),
    ]
