# Generated by Django 5.0.3 on 2024-03-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_promoter_score', '0009_userscore_is_ees_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='month',
            field=models.CharField(blank=True, db_index=True, help_text='Month of the score', max_length=20),
        ),
        migrations.AddField(
            model_name='userscore',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Year of the score', null=True),
        ),
    ]
