# Generated by Django 5.0.2 on 2024-02-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_npssurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NPSSurvey',
        ),
    ]
