# Generated by Django 5.0.2 on 2024-02-20 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_delete_npssurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbu_units', to='owner.company')),
                ('users', models.ManyToManyField(blank=True, related_name='sbu_units', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
