# Generated by Django 5.0.2 on 2024-02-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_sbu'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Date format: YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Max size: 320 x 320 px, Max file size: 750KB', max_length=255, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
