# Generated by Django 5.0.2 on 2024-02-22 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sbu_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbu_units', to='owner.sbu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sbu',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbu_units', to='owner.company'),
        ),
        migrations.AlterField(
            model_name='sbu',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='sbu_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
