# Generated by Django 5.0.2 on 2024-02-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_company_owner_customuser_sbu_units_and_more'),
        ('survey', '0021_surveyquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='chosen_survey_questions',
            field=models.ManyToManyField(blank=True, related_name='chosen_by_companies', to='survey.surveyquestion'),
        ),
    ]
