# Generated by Django 5.0.2 on 2024-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_company_chosen_survey_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
    ]
